[pytest]

addopts =
    -v
    -ra
    --strict-markers
;    --cov=src
;    --cov-report=term-missing

markers =
    # Каждый маркер на новой строке, с отступом
    smoke: Дымовые тесты для критического функционала
    regression: Полный набор регрессионных тестов
    slow: Медленные тесты (например, с доступом к сети)
    api: Тесты, взаимодействующие с внешним API
    database: Тесты, требующие доступа к БД

# Явно указываем, что тесты живут только здесь
testpaths = tests
